name: Artifacts  
on: [push]
env: 
  FILE_NAME: 'myArtifact'

jobs: 
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Upload the artifact for linux
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE_NAME }}
          path: .
